# Configuración del Sitio - SUMIX 
title: "SUMIX | Supply & Services"
description: "Suministro y procura de productos industriales y servicios especializados en Venezuela."
url: "https://sumix.com.ve"
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Datos de contacto
email: sumixca@gmail.com
rif: "J-501707413"
address: "Urbanización Los Cocales, Calle Los Robles, casa No. 154, El Tigre, Estado Anzoátegui, Venezuela."
phone: "0414-8009142"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
